namespace :add_businesses do
	task populate: :environment do
	food = Category.create(:name => "Food")
	fb = Category.create(:name => "Fashion and Beauty")
	eo = Category.create(:name => "Events and Occasions")
	other = Category.create(:name => "Other")
	home = Category.create(:name => "Home decorations")
	
	Business.create(:name => "rauo8").categories << food
Business.create(:name => "_torta").categories << food
Business.create(:name => "roshella.qtr").categories << food
Business.create(:name => "jar__sweets").categories << food
Business.create(:name => "uniquelollipopcake").categories << food
Business.create(:name => "sweeet_sugar_ ").categories << food
Business.create(:name => "yumy__yumy").categories << food
Business.create(:name => "qsr_aldiwaniya").categories << food
Business.create(:name => "tasty_sweets_qr").categories << food
Business.create(:name => "chaclate_ydooh").categories << food
Business.create(:name => "cherry_qa").categories << food
Business.create(:name => "chocolaterie_qatar").categories << food
Business.create(:name => "sukarqasab").categories << food
Business.create(:name => "specialsweety").categories << food
Business.create(:name => "makolatbintqatar").categories << food
Business.create(:name => "royal_chessecake").categories << food
Business.create(:name => "qatar_cafe ").categories << food
Business.create(:name => "tshnafa_7ala").categories << food
Business.create(:name => "jay_sweets77 ").categories << food
Business.create(:name => "tamerretab").categories << food
Business.create(:name => "aldarcafe").categories << food
Business.create(:name => "razzle_dazzle_cupcakes").categories << food
Business.create(:name => "yummy_delicious").categories << food
Business.create(:name => "unique.delicious").categories << food
Business.create(:name => "k3kycookies").categories << food
Business.create(:name => "strobareta ").categories << food
Business.create(:name => "sunshine_breakfast").categories << food
Business.create(:name => "_minisweett").categories << food
Business.create(:name => "lafoshia86").categories << food
Business.create(:name => "shklma").categories << food
Business.create(:name => "switzqa").categories << food
Business.create(:name => "pistachio_qa").categories << food
Business.create(:name => "bonapetity").categories << food
Business.create(:name => "aeybf_factory").categories << food
Business.create(:name => "ummohammed_kitchen").categories << food
Business.create(:name => "madam_suzaan").categories << food
Business.create(:name => "wrgenab87").categories << food
Business.create(:name => "gornagebstook").categories << food
Business.create(:name => "fwalti").categories << food
Business.create(:name => "edaamfood").categories << food
Business.create(:name => "alna89a").categories << food
Business.create(:name => "lepapillon__qtr").categories << food
Business.create(:name => "3usha_catering").categories << food
Business.create(:name => "mada5el_al3afya").categories << food
Business.create(:name => "breadtalkqatar").categories << food
Business.create(:name => "artsweeets").categories << food
Business.create(:name => "ajer_sweet").categories << food
"Business.create(:name => ""
mini_bitess"").categories << food"
Business.create(:name => "sweet_retreat").categories << food
Business.create(:name => "dareensweets").categories << food
Business.create(:name => "amhamad1122").categories << food
Business.create(:name => "petti_sweet").categories << food
Business.create(:name => "noonqtr_").categories << food
Business.create(:name => "le_rose_sweets").categories << food
Business.create(:name => "magictrufflesqtr").categories << food
Business.create(:name => "tasty_tart_ ").categories << food
Business.create(:name => "bon_gout").categories << food
Business.create(:name => "edible_qatar").categories << food
Business.create(:name => "bonbons_qa").categories << food
Business.create(:name => "lollicakesqa").categories << food
Business.create(:name => "sugartaste").categories << food
Business.create(:name => "fatmaalkuwaricakes").categories << food
Business.create(:name => "ibake_qtr").categories << food
Business.create(:name => "7alaqatar").categories << food
Business.create(:name => "ganache_pastries").categories << food
Business.create(:name => "mini_kitchen_").categories << food
Business.create(:name => "pralineqatar ").categories << food
Business.create(:name => "fwala").categories << food
Business.create(:name => "marmaladebakery").categories << food
Business.create(:name => "tamarasweetbites").categories << food
Business.create(:name => "shosho_al_jaidah").categories << food
Business.create(:name => "amazingcupcake2010").categories << food
Business.create(:name => "sweetmomentsq").categories << food
Business.create(:name => "ktowncupcakes").categories << food
Business.create(:name => "lasweet_").categories << food
Business.create(:name => "n_oreotruffles").categories << food
Business.create(:name => "yumylicious_ ").categories << food
"Business.create(:name => ""
simple_sweet_qtr"").categories << food"
Business.create(:name => "yaziqatar").categories << food
Business.create(:name => "homecookiesqtr").categories << food
Business.create(:name => "tawasiqatar").categories << food
Business.create(:name => "sweet.jars").categories << food
Business.create(:name => "qatari_cooking").categories << food
Business.create(:name => "stylish_girl_qtr").categories << food
Business.create(:name => "tasty_jars").categories << food
Business.create(:name => "sweet_and_cookies").categories << food
Business.create(:name => "fluffy_sweets").categories << food
Business.create(:name => "golden.kitchen").categories << food
Business.create(:name => "marmy_qtr").categories << food
Business.create(:name => "6mma6ah").categories << food
Business.create(:name => "perfect_details_").categories << food
Business.create(:name => "thegoldchocolate").categories << food
Business.create(:name => "victorian_chocolate").categories << food
Business.create(:name => "le_shiffon").categories << food
Business.create(:name => "dolcecaramelo_ ").categories << food
Business.create(:name => "chocolate_sweet3").categories << food
"Business.create(:name => ""
qatartmreya"").categories << food"
Business.create(:name => "passion_n_jars").categories << food
Business.create(:name => "vip_kitchen_qtr").categories << food
Business.create(:name => "nonitouch_qa").categories << food
Business.create(:name => "_minicherry").categories << food
Business.create(:name => "warq_enap").categories << food
"Business.create(:name => ""zee_sweett
"").categories << food"
Business.create(:name => "joz_poori").categories << food
Business.create(:name => "choco.choclate").categories << food
Business.create(:name => "spoonlady8").categories << food
Business.create(:name => "sweetrush_qa").categories << food
Business.create(:name => "um.abdallah64").categories << food
Business.create(:name => "cinnabon_homemade").categories << food
Business.create(:name => "wedamkitchen").categories << food
Business.create(:name => "just_rocky_").categories << food
Business.create(:name => "raniasecrets ").categories << fb
Business.create(:name => "samiaalsaleh").categories << fb
Business.create(:name => "lavish_makeup_artists").categories << fb
Business.create(:name => "pearlyglam").categories << fb
Business.create(:name => "afra_makeup").categories << fb
Business.create(:name => "gmoor_makeup").categories << fb
Business.create(:name => "emilia_makeup ").categories << fb
Business.create(:name => "mooody_artist").categories << fb
Business.create(:name => "enassmakeup").categories << fb
Business.create(:name => "ara_makeup").categories << fb
Business.create(:name => "rosesaloon").categories << fb
Business.create(:name => "w_makeuppp").categories << fb
Business.create(:name => "ranhalawi").categories << fb
Business.create(:name => "beautyfactory_qa").categories << fb
Business.create(:name => "muneera_makeup").categories << fb
Business.create(:name => "june_collection_ ").categories << fb
Business.create(:name => "maravilloso_boutique").categories << fb
Business.create(:name => "somaa___2").categories << fb
Business.create(:name => "jewels_makeup_").categories << fb
Business.create(:name => "isabellahaycock").categories << fb
Business.create(:name => "kamilya_87").categories << fb
Business.create(:name => "staceyjane.24").categories << fb
Business.create(:name => "dress_qatar_sale ").categories << fb
Business.create(:name => "ghinwa_eb").categories << fb
Business.create(:name => "nuha.23").categories << fb
Business.create(:name => "purple.chic").categories << fb
Business.create(:name => "glamour_qtr").categories << fb
Business.create(:name => "the_angel_rose").categories << fb
Business.create(:name => "daraatee").categories << fb
Business.create(:name => "flower_crowns_qtr").categories << fb
Business.create(:name => "mememoooon").categories << fb
Business.create(:name => "satin_colors_qtr").categories << fb
Business.create(:name => "elegant__jewelry").categories << fb
Business.create(:name => "muneera_fashion").categories << fb
Business.create(:name => "sama_accessories").categories << fb
Business.create(:name => "zainsadeq ").categories << fb
Business.create(:name => "aboudy.hairandmakeup").categories << fb
Business.create(:name => "zumrutcollection").categories << fb
Business.create(:name => "washy_line").categories << fb
Business.create(:name => "noora330").categories << fb
Business.create(:name => "the_diamond_poutiqe").categories << fb
Business.create(:name => "nstyle_qa").categories << fb
Business.create(:name => "to.be.elegant").categories << fb
Business.create(:name => "ashleigh_marchak").categories << fb
Business.create(:name => "nisrinkhalifeh").categories << fb
Business.create(:name => "om_omar_qatar").categories << fb
Business.create(:name => "the.fabulous_qtr").categories << fb
Business.create(:name => "shosho_makeup_artist").categories << fb
Business.create(:name => "creation_nkf ").categories << fb
Business.create(:name => "_nagda").categories << fb
Business.create(:name => "sheen_designs").categories << fb
Business.create(:name => "alsagha").categories << fb
Business.create(:name => "jafla.fashion").categories << fb
Business.create(:name => "line_abaya").categories << fb
Business.create(:name => "aey.official").categories << fb
Business.create(:name => "bogshti_chic").categories << fb
Business.create(:name => "blackroyaltydesign").categories << fb
Business.create(:name => "elegantcouture").categories << fb
Business.create(:name => "aljooker_qtr").categories << fb
Business.create(:name => "_dbrand_").categories << fb
Business.create(:name => "stunningqtr").categories << fb
Business.create(:name => "angelic_angelique").categories << fb
Business.create(:name => "paceeluce_qatar ").categories << fb
Business.create(:name => "roza_shoop").categories << fb
Business.create(:name => "freshlook_salon").categories << fb
Business.create(:name => "skinandsoulqtr").categories << fb
Business.create(:name => "debajcollection").categories << fb
Business.create(:name => "kharaz.qa").categories << fb
Business.create(:name => "textureqtr").categories << fb
Business.create(:name => "henna_974").categories << fb
Business.create(:name => "aey_boutique_").categories << fb
Business.create(:name => "theswan_salon").categories << fb
Business.create(:name => "glitter_q6r").categories << fb
Business.create(:name => "dunjaduxik").categories << fb
Business.create(:name => "todays_fashionq").categories << fb
Business.create(:name => "danariadthelabel").categories << fb
Business.create(:name => "patternabayas").categories << fb
Business.create(:name => "oshy.collection").categories << fb
Business.create(:name => "rebel__").categories << fb
Business.create(:name => "reemalkuwari_makeup").categories << fb
Business.create(:name => "lena_ryzhakova").categories << fb
Business.create(:name => "lina_alghawi ").categories << fb
Business.create(:name => "sha1kha_").categories << fb
Business.create(:name => "bydaleenalkhatib").categories << fb
Business.create(:name => "patricia_keller").categories << fb
Business.create(:name => "kholoudhany").categories << fb
Business.create(:name => "mayfakhry").categories << fb
Business.create(:name => "maritomaz87").categories << fb
Business.create(:name => "catherinestewart").categories << fb
Business.create(:name => "fatmamakeup_ ").categories << fb
Business.create(:name => "shalet90").categories << fb
Business.create(:name => "deedesign82").categories << fb
Business.create(:name => "laurettestar").categories << fb
Business.create(:name => "yezenianavarro").categories << fb
Business.create(:name => "makeup_byshosh").categories << fb
Business.create(:name => "a_touch_of_beauty_qatar").categories << fb
Business.create(:name => "makeup.by.qatar").categories << fb
Business.create(:name => "saramakeup_974").categories << fb
Business.create(:name => "lady_aysha").categories << fb
Business.create(:name => "brismcouture").categories << fb
Business.create(:name => "fatmamakeup").categories << fb
Business.create(:name => "stylelicious_shop").categories << fb
Business.create(:name => "pastels_qa").categories << fb
Business.create(:name => "ememakeupartist").categories << fb
Business.create(:name => "makeupbyshoosh").categories << fb
Business.create(:name => "qatarfashion").categories << fb
Business.create(:name => "mashmom.rihan.qtr").categories << fb
Business.create(:name => "wadhamakeup").categories << fb
Business.create(:name => "_bugga_boo").categories << fb
Business.create(:name => "qatarifashion").categories << fb
Business.create(:name => "lamya_bucheeri").categories << fb
Business.create(:name => "a1789_ ").categories << fb
Business.create(:name => "beauty_trove").categories << fb
Business.create(:name => "labottega_fashion").categories << fb
Business.create(:name => "salhameedi").categories << fb
Business.create(:name => "n_and_n_design").categories << fb
Business.create(:name => "syrinawilliams").categories << fb
Business.create(:name => "trinitytalentqatar").categories << fb
Business.create(:name => "f.designe").categories << fb
Business.create(:name => "themakeuprtist").categories << fb
Business.create(:name => "jackety__ ").categories << fb
Business.create(:name => "mmlka_al36wr").categories << fb
Business.create(:name => "y_collection_qa").categories << fb
Business.create(:name => "bp_abaya").categories << fb
Business.create(:name => "mommy.and.me").categories << fb
Business.create(:name => "blue_stone_ ").categories << fb
Business.create(:name => "ellefashion1").categories << fb
Business.create(:name => "brands_world1").categories << fb
Business.create(:name => "marka_style").categories << fb
Business.create(:name => "q6r_rosary").categories << fb
Business.create(:name => "ca.jewellery").categories << fb
Business.create(:name => "zaree_alwakrah ").categories << fb
Business.create(:name => "clothinglounge_qa").categories << fb
Business.create(:name => "order_station").categories << fb
Business.create(:name => "getstuff__").categories << fb
Business.create(:name => "lmsat_36riah").categories << fb
Business.create(:name => "my_section").categories << fb
Business.create(:name => "blackness_code").categories << fb
Business.create(:name => "legendqtr_8008").categories << fb
Business.create(:name => "your_shopiiz").categories << fb
Business.create(:name => "lux_qtr").categories << fb
Business.create(:name => "ze.gallery").categories << fb
Business.create(:name => "qatar_jewelry").categories << fb
Business.create(:name => "irisqatar").categories << fb
Business.create(:name => "glamourfhq").categories << fb
Business.create(:name => "al_dra3a").categories << fb
Business.create(:name => "ln_abayas").categories << fb
Business.create(:name => "thedress._ ").categories << fb
Business.create(:name => "signaturebyfatma").categories << fb
Business.create(:name => "koorboutique").categories << fb
Business.create(:name => "fashionista.baby").categories << fb
Business.create(:name => "printaty").categories << fb
Business.create(:name => "everything_u.need").categories << fb
"Business.create(:name => ""d_a_botteca
"").categories << fb"
Business.create(:name => "noun_makeup_artist_").categories << fb
"Business.create(:name => ""a__malikati
"").categories << fb"
Business.create(:name => "vintage.qtr").categories << fb
Business.create(:name => "dra3at_7zaya").categories << fb
Business.create(:name => "brooch.86r").categories << fb
Business.create(:name => "mc_974").categories << fb
Business.create(:name => "talween_qa").categories << fb
Business.create(:name => "a_and_a_boutique").categories << fb
Business.create(:name => "violaqtr").categories << fb
Business.create(:name => "catdeluxe95_women").categories << fb
Business.create(:name => "thepoint____").categories << fb
Business.create(:name => "cute_style_qtr").categories << fb
Business.create(:name => "ebda3ate_qatar").categories << eo
Business.create(:name => "gore22777").categories << eo
Business.create(:name => "fantasy_qat").categories << eo
Business.create(:name => "ladybirdfavors").categories << eo
Business.create(:name => "occasions_qtr ").categories << eo
Business.create(:name => "jadorecatering").categories << eo
Business.create(:name => "r_souvenirs").categories << eo
Business.create(:name => "twze3aty_qtr ").categories << eo
Business.create(:name => "sogtee_").categories << eo
Business.create(:name => "hssqatar").categories << eo
Business.create(:name => "flowercornerqtr").categories << eo
Business.create(:name => "_aalsana3_ ").categories << eo
Business.create(:name => "blossom_qa").categories << eo
Business.create(:name => "sugar.rush_qa").categories << eo
Business.create(:name => "lavenderqatar1").categories << eo
Business.create(:name => "alhanevents").categories << eo
Business.create(:name => "final_touch_qatar").categories << eo
Business.create(:name => "vanilla_lane").categories << eo
Business.create(:name => "sogha_ ").categories << eo
Business.create(:name => "finaltouch_qa").categories << eo
Business.create(:name => "most_beautiful_ever").categories << eo
Business.create(:name => "alshouq_flower").categories << eo
Business.create(:name => "noof_designs").categories << eo
Business.create(:name => "tulip.design ").categories << eo
Business.create(:name => "cadeau_de_paris").categories << eo
"Business.create(:name => ""bloona2
"").categories << eo"
"Business.create(:name => ""bubbles__balloons
"").categories << eo"
Business.create(:name => "al_shathelya").categories << eo
Business.create(:name => "ipatterns_").categories << eo
Business.create(:name => "raffeedofficial").categories << other
Business.create(:name => "i.shopi").categories << other
Business.create(:name => "radio_london").categories << other
Business.create(:name => "aliphotoarts ").categories << other
Business.create(:name => "sjadatvip").categories << other
Business.create(:name => "purityofphotography").categories << other
Business.create(:name => "crossfitoryx").categories << other
Business.create(:name => "moeramadan").categories << other
Business.create(:name => "nairoozphotography").categories << other
Business.create(:name => "special_qtr_shop").categories << other
Business.create(:name => "almhastore").categories << other
Business.create(:name => "brio_autocare_qtr").categories << other
Business.create(:name => "lee8yta").categories << other
Business.create(:name => "catsqata").categories << other
Business.create(:name => "my__home").categories << home
Business.create(:name => "fantasia_tables").categories << home
Business.create(:name => "n_and_s_qatar").categories << home
Business.create(:name => "dalilascorner").categories << home
Business.create(:name => "tanateef.qa").categories << home
Business.create(:name => "qatar_dalh").categories << home
Business.create(:name => "plumage_sd").categories << home
	end
end